// const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
// const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
// const GET_DATA_FAIL = 'GET_DATA_FAIL';

const CART_FETCH_SUCCESS = 'CART_FETCH_SUCCESS';
const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
const FETCH_REQUEST = 'FETCH_REQUEST';
const FETCH_FAIL = 'FETCH_FAIL';

const CART_UPDATE_REQUEST = 'CART_UPDATE_REQUEST';
const CART_UPDATE_SUCCESS = 'CART_UPDATE_SUCCESS';
const CART_UPDATE_FAIL = 'CART_UPDATE_FAIL';

export {
   //    GET_DATA_REQUEST,
   //    GET_DATA_SUCCESS,
   //    GET_DATA_FAIL,
   FETCH_REQUEST,
   FETCH_FAIL,
   CART_FETCH_SUCCESS,
   CART_UPDATE_REQUEST,
   CART_UPDATE_SUCCESS,
   CART_UPDATE_FAIL,
   FETCH_PRODUCTS_SUCCESS,
};
