const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
const FETCH_FAIL = 'FETCH_FAIL';

// NEw
const FETCH_REQUEST = 'FETCH_REQUEST';
const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';

export {
   GET_PRODUCTS_REQUEST,
   GET_PRODUCTS_SUCCESS,
   FETCH_FAIL,
   FETCH_REQUEST,
   FETCH_PRODUCTS_SUCCESS,
   FETCH_PRODUCTS_FAIL,
};
